name: Platformer Generated production Build
'on':
  push:
    tags:
      - '*'
jobs:
  build:
    runs-on:
      - ubuntu-latest
    env:
      SERVICE_NAME: ghcr.io/sliit-foss/sliitfoss
      CONTAINER_REGISTRY: ghcr.io
    steps:
      - uses: actions/checkout@v2
      - name: Set Version
        id: event-version
        run: echo ::set-output name=SOURCE_TAG::${GITHUB_REF#refs/tags/}
      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.CONTAINER_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.DOCKER_PASSWORD_1D0EB88E_20A8_4DB1_AFB3_968AA9026A4C }}
      - name: Build the Docker image
        run: docker build --tag ${SERVICE_NAME}:${{steps.event-version.outputs.SOURCE_TAG }} --file Dockerfile .
      - name: GitHub Image Push
        run: docker push $SERVICE_NAME:${{steps.event-version.outputs.SOURCE_TAG }}
      - name: Platformer Deploy
        uses: platformer-com/build-deploy-action@v1
        with:
          org-id: ${{secrets.ORG_ID_40A1DDFC_9E44_4A93_A6A0_C8D68AAA6420}}
          project-id: ${{secrets.PROJECT_ID_40A1DDFC_9E44_4A93_A6A0_C8D68AAA6420}}
          token: ${{secrets.AUTOGENERATED_CICD_40A1DDFC_9E44_4A93_A6A0_C8D68AAA6420}}
          image-name: ${{env.SERVICE_NAME}}
          tag: ${{steps.event-version.outputs.SOURCE_TAG }}
          container-id: bd3ca5e8-cd8a-4fc3-baa8-1f586e19a1e0
